<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.web>
    <!-- Não resolve o FastCGI, mas pode ficar -->
    <httpRuntime executionTimeout="600" />
  </system.web>

  <system.webServer>

    <!-- FastCGI com timeouts folgados -->
    <fastCgi>
      <application
        fullPath="D:\taskfy\venv\Scripts\python.exe"
        arguments="D:\taskfy\venv\Lib\site-packages\wfastcgi.py"
        activityTimeout="00:10:00"
        requestTimeout="00:10:00"
        idleTimeout="00:10:00"
        instanceMaxRequests="100000">
        <environmentVariables>
          <environmentVariable name="DJANGO_SETTINGS_MODULE" value="taskfy.settings" />
          <environmentVariable name="PYTHONPATH" value="D:\taskfy" />
          <environmentVariable name="WSGI_HANDLER" value="django.core.wsgi.get_wsgi_application()" />
          <!-- log para capturar tracebacks do wfastcgi -->
          <environmentVariable name="WSGI_LOG" value="D:\taskfy\logs\wfastcgi.log" />
          <environmentVariable name="PYTHONUNBUFFERED" value="1" />
        </environmentVariables>
      </application>
    </fastCgi>

    <!-- Deixe seu handler como está -->
    <handlers>
      <add name="Django Handler"
           path="*"
           verb="*"
           modules="FastCgiModule"
           scriptProcessor="D:\taskfy\venv\Scripts\python.exe|D:\taskfy\venv\Lib\site-packages\wfastcgi.py"
           resourceType="Unspecified" />
    </handlers>

    <!-- Deixe o Django devolver os próprios erros -->
    <httpErrors existingResponse="PassThrough" />
  </system.webServer>
</configuration>
